apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: g-c-64-tpus-dest
  namespace: default
spec:
  host: g-c-64-tpus
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      tcp:
        maxConnections: 1024
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 10
