apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: default
spec:
  provider:
    gcpsm:
      projectID: "your-gcp-project-id"
      auth:
        workloadIdentity:
          clusterLocation: "us-central2"
          clusterName: "g-c-64-tpus-cluster"
          serviceAccountRef:
            name: ksa-secret-manager
