apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: g-c-64-tpus-monitor
  namespace: default
  labels:
    release: prometheus-stack
spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: g-c-64-tpus
    endpoints:
    - port: http
      interval: 15s
      path: /metrics
